name: portfolio_app
description: "portfolio app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '3.22.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # base
  path: ^1.9.0
  go_router: ^13.1.0
  # logger
  logger: ^2.0.2+1
  logging: ^1.2.0
  stack_trace: ^1.11.1
  # state manager
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  state_notifier: ^1.0.0
  riverpod_annotation: ^2.3.4
  mutex: ^3.1.0
  # model generate
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  # setting
  intro_slider: ^4.2.1
  collection: ^1.18.0
  http: ^1.2.0
  flutter_cache_manager: ^3.3.1
  clock: ^1.1.1
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3
  # login access_token 등 관리
  flutter_secure_storage: ^9.2.0
  # loading
  flutter_easyloading: ^3.0.5
  # version check && upgrade
  upgrader: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^2.4.1
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  # version checker
  build_version: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: calsans
      fonts:
        - asset: fonts/CalSans-SemiBold.ttf
          weight: 700
    - family: inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500

flutter_gen:

